# Generated by Django 3.2.8 on 2021-12-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211210_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='wash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wash'),
        ),
    ]
