# Generated by Django 3.2.8 on 2021-12-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reservation_wash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='name',
        ),
    ]
