# Generated by Django 3.2.8 on 2021-12-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_reservation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wash',
            name='slots',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qr_image',
            field=models.ImageField(blank=True, default='qr.jpg', null=True, upload_to='qr'),
        ),
    ]
