# Generated by Django 3.2.8 on 2021-12-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211211_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='qr_image',
            field=models.ImageField(blank=True, default='qr.png', null=True, upload_to='media/'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wash', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wash')),
            ],
        ),
    ]
